ServiceMaps:
  serviceName: product
  version: 1.0.0
  mappings:
    - topic: save-product-variant-topic
      configKey: INDEX
      indexes:
        - name: productVariantIndex-v1
          type: productVariant
          id: $.*.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.*.auditDetails.createdTime
    - topic: save-product-topic
      configKey: INDEX
      indexes:
        - name: productIndex-v1
          type: product
          id: $.*.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.*.auditDetails.createdTime
    - topic: update-product-topic
      configKey: INDEX
      indexes:
        - name: productUpdateIndex-v1
          type: product-update
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime
    - topic: update-product-variant-topic
      configKey: INDEX
      indexes:
        - name: productVariantUpdateIndex-v1
          type: product-variant-update
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime